version: "3.2"
services:
  db:
    restart: always
    image: postgres:10.1-alpine
    container_name: corpjukdev_pg01
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser123
    volumes:
      - ./pg-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - main
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: corpjukdev_dj01
    environment:
      - DJANGO_SETTINGS_MODULE=eatplants.settings.prod
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./static:/app/static
    networks:
      - main
    depends_on:
      - db
    env_file:
      - .env
  nginx:
    restart: always
    image: nginx:1.15-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    container_name: corpjukdev_ng01
    volumes:
      - ./config/nginx-prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/corpjukdev/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main
    depends_on:
      - app
      - certbot
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"    
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - main
networks:
  main: